#!/usr/bin/env bash
set -euo pipefail

echo "🤖 Preenchendo .env.local automaticamente"

read -rp "NEXT_PUBLIC_SUPABASE_URL: " NEXT_PUBLIC_SUPABASE_URL
read -rp "NEXT_PUBLIC_SUPABASE_ANON_KEY: " NEXT_PUBLIC_SUPABASE_ANON_KEY
read -rp "SUPABASE_SERVICE_ROLE_KEY: " SUPABASE_SERVICE_ROLE_KEY
read -rp "STRIPE_SECRET_KEY: " STRIPE_SECRET_KEY
read -rp "STRIPE_WEBHOOK_SECRET: " STRIPE_WEBHOOK_SECRET

cat > .env.local <<EOV
# Subclue local environment variables

NEXT_PUBLIC_SUPABASE_URL=\${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=\${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=\${SUPABASE_SERVICE_ROLE_KEY}
STRIPE_SECRET_KEY=\${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=\${STRIPE_WEBHOOK_SECRET}
EOV

echo "✅  .env.local criado/preenchido com sucesso!"
